### PR TITLE
chore(publish): disable NuGet package restore

### PR DESCRIPTION
**Pull request by BrainCrumbz**
This PR aims at removing nuget restore and local nuget copy, to address an issue you experienced weeks ago on CI server. Having a local nuget copy is currently discouraged, while each environment (e.g. CI build server) should use its local nuget copy and perform an initial package restore step.

Just I'm not sure about the changes in build.ps1, maybe you want to have a double look at that and test it, as I'm not sure on how you use that script. Basically, with those changes, nuget executable is required to be on path otherwise the script would fail.

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
Strangely enough, [CI build details](https://ci.appveyor.com/project/shiftkey/reactive-eventaggregator/build/1.1.42) reports two big red areas and a final warning `No artifacts found matching 'Reactive.EventAggregator.*.nupkg' path`, but still build result is set as successful O.o

**Comment by BrainCrumbz** [comment]
@shiftkey any chance you could publish a new NuGet package beside this PR, just to have a version compatible with recent Rx.NET ? Thank you

**Comment by shiftkey** [comment]
@BrainCrumbz yeah, I'll publish a preview package now - had to tweak a couple of things to get it building on my side.

**Comment by shiftkey** [comment]
@BrainCrumbz would you be opposed to me replacing that `build.ps1` with a [CAKE](http://cakebuild.net/) build script? There's lots of things in-the-box that are easier than me re-implementing them as I have here...

**Comment by BrainCrumbz** [comment]
TBH, no opposition from here.  
Not sure what are the implications of switching from PS1 script to CAKE script, but we in my team don't plan to run *a lot* of builds here 😃 ... just be able to use Reactive.EventAggregator with recente Rx.NET and, sure, contribute along if we can.

**Comment by shiftkey** [comment]
@BrainCrumbz cool, leave it with me. Ultimately the build issues you're seeing are likely due to that script being stale. Shouldn't be too hard to replace with something more battle-tested...

**Comment by shiftkey** [comment]
Closing this out in favour of #20

**Pull request closed without merging**
